/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.javamaven.graphics;

import com.javamaven.connect.DataConnection;
import com.javamaven.connect.LoadData;
import com.javamaven.controller.controller;
import com.javamaven.dao.GiaoDichDao;
import com.javamaven.entity.GD_GUIRUT;
import java.util.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class frmGuiRut extends javax.swing.JFrame {

    private DefaultTableModel tableGuiRut;

    /**
     * Creates new form frmGuiRut
     */
    public frmGuiRut() {
        initComponents();
        tableGuiRut = (DefaultTableModel) tbl_GR.getModel();
        setExtendedState(frmGuiRut.MAXIMIZED_BOTH);

        List<String> list = LoadData.getLoaiGiaoDich();
        for (String s : list) {
            cbbLOAIGD.addItem(s);
        }
        btnGUITIEN.setEnabled(false);
        btnRUTTIEN.setEnabled(false);
        txtMANV.setEnabled(false);
        txtSOTIEN.setEnabled(false);
        txtSOTK.setEnabled(false);
        dateGD.setEnabled(false);
        cbbLOAIGD.setEnabled(false);
        cbbLOAIGD.setSelectedItem(null);
        showData();
    }

    private void showData() {
        new LoadData();
        tableGuiRut.setRowCount(0);
        int dem = 1;
        for (GD_GUIRUT gr : controller.arrayListGuiRut) {
            tableGuiRut.addRow(new Object[]{dem++, gr.getMAGD(), gr.getSOTK(), gr.getLOAIGD(), gr.getNGAYGD(), gr.getSOTIEN(), gr.getMANV()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_GR = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSOTK = new javax.swing.JTextField();
        txtSOTIEN = new javax.swing.JTextField();
        txtMANV = new javax.swing.JTextField();
        cbbLOAIGD = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dateGD = new com.toedter.calendar.JDateChooser();
        btnGUITIEN = new javax.swing.JButton();
        btnRUTTIEN = new javax.swing.JButton();
        btnCHON = new javax.swing.JButton();
        btnGUITIEN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(13, 13));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIAO DỊCH GỬI RÚT");

        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbl_GR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "MAGD", "SOTK", "LOAIGD", "NGAYGD", "SOTIEN", "MANV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_GR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_GRMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_GR);

        jLabel2.setText("Thông tin tài khoản:");

        jLabel3.setText("SOTK:");

        jLabel4.setText("SOTIEN:");

        jLabel6.setText("MANV:");

        jLabel7.setText("NGAYGD:");

        cbbLOAIGD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GT", "RT" }));
        cbbLOAIGD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLOAIGDItemStateChanged(evt);
            }
        });
        cbbLOAIGD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbLOAIGDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbbLOAIGDMouseReleased(evt);
            }
        });

        jLabel8.setText("LOAIGD:");

        dateGD.setDateFormatString("yyyy-MM-dd");

        btnGUITIEN.setText("GỬI TIỀN");
        btnGUITIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUITIENActionPerformed(evt);
            }
        });

        btnRUTTIEN.setText("RÚT TIỀN");
        btnRUTTIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUTTIENActionPerformed(evt);
            }
        });

        btnCHON.setText("CHỌN GIAO DỊCH");
        btnCHON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCHONActionPerformed(evt);
            }
        });

        btnGUITIEN1.setText("RESET");
        btnGUITIEN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUITIEN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSOTK, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSOTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCHON, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(cbbLOAIGD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGUITIEN)
                                .addGap(37, 37, 37)
                                .addComponent(btnRUTTIEN))
                            .addComponent(btnGUITIEN1))))
                .addGap(0, 221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSOTK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLOAIGD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGUITIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRUTTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSOTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCHON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGUITIEN1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateGD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmHome home = new frmHome();
        home.setLocationRelativeTo(null);
        home.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_GRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_GRMousePressed
        int row = tbl_GR.getSelectedRow();
        txtSOTK.setText((String) tbl_GR.getValueAt(row, 2));
        cbbLOAIGD.setSelectedItem((String) tbl_GR.getValueAt(row, 3));
        dateGD.setDate((Date) tbl_GR.getValueAt(row, 4));
        long SOTIEN = (long) tbl_GR.getValueAt(row, 5);

        txtSOTIEN.setText(String.valueOf(SOTIEN));
        txtMANV.setText((String) tbl_GR.getValueAt(row, 6));
        btnGUITIEN.setEnabled(false);
        btnRUTTIEN.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_tbl_GRMousePressed

    private void btnCHONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCHONActionPerformed
        String s = "";
        txtSOTIEN.setText(s);
        txtSOTK.setText(s);
        cbbLOAIGD.setSelectedItem(null);
        dateGD.setDate(null);
        txtMANV.setEnabled(false);
        txtSOTIEN.setEnabled(true);
        txtSOTK.setEnabled(true);
        dateGD.setEnabled(false);
        LocalDate currentDate = LocalDate.now();
        Date date = (Date) Date.from(currentDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        btnCHON.setEnabled(false);
        dateGD.setDate(date);
        cbbLOAIGD.setEnabled(true);
        txtMANV.setText(DataConnection.mUsername);
// TODO add your handling code here:
    }//GEN-LAST:event_btnCHONActionPerformed

    private void cbbLOAIGDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLOAIGDMousePressed

// TODO add your handling code here:
    }//GEN-LAST:event_cbbLOAIGDMousePressed

    private void cbbLOAIGDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbLOAIGDMouseReleased

    }//GEN-LAST:event_cbbLOAIGDMouseReleased

    private void cbbLOAIGDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLOAIGDItemStateChanged
        if (cbbLOAIGD.getSelectedItem() != null) {
            String CHON = (String) cbbLOAIGD.getSelectedItem();

            if (CHON.equals("GT")) {
                btnGUITIEN.setEnabled(true);
                btnRUTTIEN.setEnabled(false);
            } else if (CHON.equals("RT")) {
                btnRUTTIEN.setEnabled(true);
                btnGUITIEN.setEnabled(false);
            } else {
                System.err.println("HẾT");
            }
        }// TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_cbbLOAIGDItemStateChanged

    private void btnGUITIEN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUITIEN1ActionPerformed
        btnGUITIEN.setEnabled(false);
        String s = "";
        txtSOTIEN.setText(s);
        txtSOTK.setText(s);
        cbbLOAIGD.setSelectedItem(null);
        dateGD.setDate(null);
        txtMANV.setText(s);
        btnRUTTIEN.setEnabled(false);
        txtMANV.setEnabled(false);
        txtSOTIEN.setEnabled(false);
        txtSOTK.setEnabled(false);
        dateGD.setEnabled(false);
        cbbLOAIGD.setEnabled(false);
        cbbLOAIGD.setSelectedItem(null);  
        btnCHON.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnGUITIEN1ActionPerformed

    private void btnGUITIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUITIENActionPerformed
        String LOAIGD = (String) cbbLOAIGD.getSelectedItem();
        long SOTIEN = Long.parseLong(txtSOTIEN.getText());
        GiaoDichDao.exec_GDGuiRut(txtSOTK.getText(), LOAIGD, SOTIEN, txtMANV.getText());
        int check = GiaoDichDao.getCheck();
        switch (check) {
             case 0 ->
                JOptionPane.showMessageDialog(null, "Gửi tiền thành công");
            case 1 ->
                JOptionPane.showMessageDialog(null, "SOTK không tồn tại");
            case 2 ->
                JOptionPane.showMessageDialog(null, "Gửi tiền thất bại");
           
        }
         btnGUITIEN.setEnabled(false);
        String s = "";
        txtSOTIEN.setText(s);
        txtSOTK.setText(s);
        cbbLOAIGD.setSelectedItem(null);
        dateGD.setDate(null);
        txtMANV.setText(s);
        btnRUTTIEN.setEnabled(false);
        txtMANV.setEnabled(false);
        txtSOTIEN.setEnabled(false);
        txtSOTK.setEnabled(false);
        dateGD.setEnabled(false);
        cbbLOAIGD.setEnabled(false);
        cbbLOAIGD.setSelectedItem(null); 
        showData();

// TODO add your handling code here:
    }//GEN-LAST:event_btnGUITIENActionPerformed

    private void btnRUTTIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUTTIENActionPerformed
String LOAIGD = (String) cbbLOAIGD.getSelectedItem();
        long SOTIEN = Long.parseLong(txtSOTIEN.getText());
        GiaoDichDao.exec_GDGuiRut(txtSOTK.getText(), LOAIGD, SOTIEN, txtMANV.getText());
        int check = GiaoDichDao.getCheck();
        switch (check) {
             case 0 ->
                JOptionPane.showMessageDialog(null, "Rút tiền thành công");
            case 1 ->
                JOptionPane.showMessageDialog(null, "SOTK không tồn tại");         
            case 3 ->
                JOptionPane.showMessageDialog(null, "Số dư không đủ");
            case 4 ->
                JOptionPane.showMessageDialog(null, "Rút tiền thất bại");

        }
         btnGUITIEN.setEnabled(false);
        String s = "";
        txtSOTIEN.setText(s);
        txtSOTK.setText(s);
        cbbLOAIGD.setSelectedItem(null);
        dateGD.setDate(null);
        txtMANV.setText(s);
        btnRUTTIEN.setEnabled(false);
        txtMANV.setEnabled(false);
        txtSOTIEN.setEnabled(false);
        txtSOTK.setEnabled(false);
        dateGD.setEnabled(false);
        cbbLOAIGD.setEnabled(false);
        cbbLOAIGD.setSelectedItem(null); 
        showData();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRUTTIENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGuiRut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGuiRut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGuiRut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGuiRut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGuiRut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCHON;
    private javax.swing.JButton btnGUITIEN;
    private javax.swing.JButton btnGUITIEN1;
    private javax.swing.JButton btnRUTTIEN;
    private javax.swing.JComboBox<String> cbbLOAIGD;
    private com.toedter.calendar.JDateChooser dateGD;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_GR;
    private javax.swing.JTextField txtMANV;
    private javax.swing.JTextField txtSOTIEN;
    private javax.swing.JTextField txtSOTK;
    // End of variables declaration//GEN-END:variables
}
